### ISSUE TITLE
getting crashed

### ISSUE THREAD

**Issue by Vikash84** [johnne/tango#5]
Making lineages:   7%|██▍                             | 20724/277641 [00:14<02:51, 1497.39 taxids/s]multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/vsingh/.conda/envs/tango/lib/python3.5/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/home/vsingh/.conda/envs/tango/lib/python3.5/site-packages/tango/assign.py", line 490, in process_lineages
    x = add_names(x, taxid, ncbi_taxa)
  File "/home/vsingh/.conda/envs/tango/lib/python3.5/site-packages/tango/assign.py", line 114, in add_names
    if t < 0:
  File "/home/vsingh/.conda/envs/tango/lib/python3.5/site-packages/pandas/core/generic.py", line 1576, in __nonzero__
    .format(self.__class__.__name__))
ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/vsingh/.conda/envs/tango/bin/tango", line 12, in <module>
    sys.exit(main())
  File "/home/vsingh/.conda/envs/tango/lib/python3.5/site-packages/tango/__main__.py", line 283, in main
    args.func(args)
  File "/home/vsingh/.conda/envs/tango/lib/python3.5/site-packages/tango/__main__.py", line 77, in assign_taxonomy
    args.rank_thresholds, args.taxdir, args.sqlitedb, args.chunksize, args.cpus)
  File "/home/vsingh/.conda/envs/tango/lib/python3.5/site-packages/tango/assign.py", line 776, in parse_hits
    lineage_df, name_dict = make_lineage_df(taxids, taxdir, sqlitedb, reportranks, cpus)
  File "/home/vsingh/.conda/envs/tango/lib/python3.5/site-packages/tango/assign.py", line 561, in make_lineage_df
    unit=" taxids", ncols=100))
  File "/home/vsingh/.conda/envs/tango/lib/python3.5/site-packages/tqdm/std.py", line 1093, in __iter__
    for obj in iterable:
  File "/home/vsingh/.conda/envs/tango/lib/python3.5/multiprocessing/pool.py", line 731, in next
    raise value
ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

**Comment by johnne** [comment]
Hi @Vikash84,
Sorry about not getting back to you earlier.  

What version of tango were you using for this? Is it possible for you to upload some parts of the input used that caused this error?

**Comment by Vikash84** [comment]
I have observed when data size is small it work s fine, but for large data size it generally get crashed.

At that time i was using tango 0.5.7.

**Comment by johnne** [comment]
From the error message I get a sense it may be related to missing and/or duplicate taxid entries in some way. What database did you use when this happened? Could you try with the latest version? (Please note that the package has changed name to `contigtax`)

**Comment by Vikash84** [comment]
I was using NCBI nr database.  Sure I will give a try with latest version i.e contigtax.

**Comment by johnne** [comment]
Thanks! Let me know how it goes.
